### ISSUE TITLE
Fill env.example with values

### ISSUE THREAD

**Issue by chestnyh** [Andrij-Maksymyshyn/blog#19]
You should fill your env.example file with some default values
Something like:
```
PORT=3000
DB_HOST=localhost
.....
```
To be able to set up server quickly
Read this https://medium.com/the-node-js-collection/making-your-node-js-work-everywhere-with-environment-variables-2da8cdf6e786

There is env.example example in article. And good to read the whole article

**Comment by Andrij-Maksymyshyn** [comment]
done
