### ISSUE TITLE
Add some testing tool

### ISSUE THREAD

**Issue by chestnyh** [Andrij-Maksymyshyn/blog#6]
We need to add some testing tool for project.
There are two possible ways: 
1) Plug in swagger to be able to test your endpoints (preferable, but takes more time). 
     Useful links: 
     1) https://www.npmjs.com/package/swagger-ui-express
     2) https://swagger.io/docs/specification/about/
2) Create some postman collection and import it to repository(easiest way)

**Comment by Andrij-Maksymyshyn** [comment]
done
